name: Gasha Clip

on:
  workflow_dispatch:
  schedule: 
    - cron: "0 15 * * *"  
  
jobs:
  gashaclip:
    runs-on: ubuntu-latest

    steps:
      - name: Clone Private Repo
        env:
          PAT_GITHUB: ${{ secrets.PAT_GITHUB }}
        run: |
          git clone https://x-access-token:${PAT_GITHUB}@github.com/iamCristYE/nogi-sp.git
          cd nogi-sp
          apt install ffmpeg

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.14' # Specify the Python version you need
   
      - name: Run Python script
        run: |
          pip install requests
          python3 -m pip install -U "yt-dlp[default]"
          cd nogi-sp
          python gashaclip.py

      - name: Commit and Push Changes
        run: |
          cd nogi-sp
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data.json
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Check Gasha Clip - $(TZ=Asia/Tokyo date)"
            attempt=0
            max_attempts=5
            until [ $attempt -ge $max_attempts ]
            do
              if git push; then
                echo "Changes committed and pushed."
                break
              else
                attempt=$((attempt+1))
                echo "Push failed. Attempt $attempt/$max_attempts. Running git pull and retrying..."
                git pull --rebase
                sleep 10
              fi
            done
            if [ $attempt -eq $max_attempts ]; then
              echo "Push failed after $max_attempts attempts."
              exit 1
            fi
          else
            echo "No changes to commit."
          fi
